# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='family',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
