# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_student_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.Cource')),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='question_text',
            new_name='name',
        ),
        migrations.AddField(
            model_name='studentcources',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.Student'),
        ),
    ]
